### ISSUE TITLE
Make Repo.filter() work with Ecto.Query (Ecto 3.4.4)

### ISSUE THREAD

**Issue by ekarak** [valyukov/ex_sive#18]
Work in progress, right now Repo.filter() chokes on plain queries, because aliases might be already defined.
Quick and dirty changes I made to make this work: 
```
12:30 $ git diff
diff --git a/lib/ex_sieve.ex b/lib/ex_sieve.ex
index 70318ae..05a4365 100644
--- a/lib/ex_sieve.ex
+++ b/lib/ex_sieve.ex
@@ -47,6 +47,6 @@ defmodule ExSieve do
   defp result({:error, reason}, _queryable), do: {:error, reason}
   defp result({:ok, groupings, sorts}, queryable), do: Builder.call(queryable, groupings, sorts)
 
-  defp extract_schema(%{from: {_, schema}}), do: schema
+  defp extract_schema(%{from: %{source: {_, schema}}}), do: schema
   defp extract_schema(schema), do: schema
 end
diff --git a/lib/ex_sieve/builder/join.ex b/lib/ex_sieve/builder/join.ex
index bcc48bc..1b27fde 100644
--- a/lib/ex_sieve/builder/join.ex
+++ b/lib/ex_sieve/builder/join.ex
@@ -61,12 +61,17 @@ defmodule ExSieve.Builder.Join do
   end
 
   defp apply_join({parent, relation} = pr, query) do
-    query
-    |> Macro.escape()
-    |> Join.build(:inner, join_binding(parent), expr(relation), nil, nil, join_as(pr), nil, nil, __ENV__)
-    |> elem(0)
-    |> Code.eval_quoted()
-    |> elem(0)
+    cond do
+      Map.has_key?(query.aliases, relation) ->
+        query
+      true ->
+        query
+        |> Macro.escape()
+        |> Join.build(:inner, join_binding(parent), expr(relation), nil, nil, join_as(pr), nil, nil, __ENV__)
+        |> elem(0)
+        |> Code.eval_quoted()
+        |> elem(0)
+    end
   end
```

**Comment by albertored** [comment]
Could you please attach an example of some failing code?

**Comment by ekarak** [comment]
First problem is the pattern match on the Ecto.Query struct which is different when it tries to `extract_schema` from the root model of the query:
```
    query =
      from participants in Participant,
      inner_join: persons        in assoc(participants, :person),  as: :person,
      inner_join: seasons        in assoc(participants, :season),  as: :season,
...
iex(155)> query |> Repo.filter(%{"season_sportevents_id_eq" =>  "8"})  
** (ArgumentError) you attempted to apply a function on #Ecto.Query<from p0 in Hierarchetta.Hierarchy.Participant, join: p1 in assoc(p0, :person), join: s2 in assoc(p0, :season), join: c3 in assoc(s2, :competition), as: :competition, left_join: s4 in assoc(s2, :sportevents), left_join: c5 in assoc(s4, :competitors), as: :competitor, left_join: s6 in assoc(c5, :statistics), as: :statistic, left_join: s7 in assoc(s6, :statistic_type), as: :statistic_type, where: c5.participant_id == p0.id, preload: [competitors: {c5, [sportevent: s4, statistics: {s6, [statistic_type: s7]}]}, person: p1, season: {s2, [competition: c3]}]>. Modules (the first argument of apply) must always be an atom
    :erlang.apply(#Ecto.Query<from p0 in Hierarchetta.Hierarchy.Participant, join: p1 in assoc(p0, :person), join: s2 in assoc(p0, :season), join: c3 in assoc(s2, :competition), as: :competition, left_join: s4 in assoc(s2, :sportevents), left_join: c5 in assoc(s4, :competitors), as: :competitor, left_join: s6 in assoc(c5, :statistics), as: :statistic, left_join: s7 in assoc(s6, :statistic_type), as: :statistic_type, where: c5.participant_id == p0.id, preload: [competitors: {c5, [sportevent: s4, statistics: {s6, [statistic_type: s7]}]}, person: p1, season: {s2, [competition: c3]}]>, :__schema__, [:fields])
```

Once we fix the pattern matching, the second problem is:
```
iex(160)> query |> Repo.filter(%{"season_sportevents_id_eq" =>  "8"}) 
** (Ecto.Query.CompileError) alias `:season` already exists
    (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.3) lib/code.ex:706: Code.eval_quoted/3
    (ex_sieve 0.6.1) deps/ex_sieve/lib/ex_sieve/builder/join.ex:73: ExSieve.Builder.Join.apply_join/2
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_sieve 0.6.1) lib/ex_sieve/builder.ex:10: ExSieve.Builder.call/3```
```
with my change it introduces a second unaliased join on the same table on which the filter is being applied:
```
iex(161)> query |> Repo.filter(%{"season_sportevents_id_eq" =>  "8"}) 
#Ecto.Query<from p0 in Hierarchetta.Hierarchy.Participant, join: p1 in assoc(p0, :person), as: :person,
 join: s2 in assoc(p0, :season), as: :season, ...
 left_join: s4 in assoc(s2, :sportevents),
 ..., 
join: s8 in assoc(s2, :sportevents), as: :season_sportevents, where: c5.participant_id == p0.id,
 where: s8.id == ^"8",
 preload: [competitors: {c5, [sportevent: s4, statistics: {s6, [statistic_type: s7]}]}, person: p1, season: {s2, [competition: c3]}]>
iex(162)> 
```
Tables s4 (preexisting aliased join in the incoming query) and s8 (introduced from ex_sieve `Repo.filter` are the same table, though effectively joined correctly.

**Comment by ekarak** [comment]
(FYI, ecto 3.4.4, ex_sieve on the nested_queries branch, will update this now to 0.7.0)

**Comment by albertored** [comment]
Ok, understood the problem, I will take a look. 

My main concern is that I would like to avoid to use ecto internal APIs as much as possible

**Comment by albertored** [comment]
Just pèushed a branch with the fix, if you want to give it a try then I will merge and release a new version.

**Comment by ekarak** [comment]
thanks, will take a look

**Comment by ekarak** [comment]
Hi Alberto, the code in the branch works beautifully (its able to handle Exto.Query structs) but it still exhibits the multiple joins issue (see the example of aliases s8 and s4 above), which means the same table is being joined twice (or more), and query filters are applied on the joins inserted by the Repo.filter call. This is not a problem for most use cases, but in case you need to back-track on joins (ie when you walk UP the hierarchy) then it becomes a real issue as the query will return rows that should have been filtered.

Fortunately this is not a blocker, as *there's a workaround*, it simply involves naming the aliases in the query that I feed into Repo.filter/2 in same way as the ex_sieve library expects them. This needs to be documented probably, so I think of writing some documentation on it.

Again, many thanks for your prompt response!

**Comment by albertored** [comment]
Yes, this is a limitation but as far as I know there is no API in ecto that allows a more strict check on the present joins. I have added [some documentation](https://github.com/valyukov/ex_sieve/blob/patch/18-existent-joins/lib/ex_sieve.ex#L47) about it but feel free to send a PR for improving it if you think it's not sufficiently clear.

Thank you for testing it!
